### ISSUE TITLE
About generating cpp project

### ISSUE THREAD

**Issue by suzumiyasmith** [pure11/pure11#1]
I am studying in computational math and tired dealing with tonnes of coursework forced to be coded in `c++`. Debugging and dealing with memory are quite annoying in `c++`. Hence, I turned to `pure11`.

Is there any advice for generating pure `c++` project, which seems like written in `c++`?

Sorry for bothering for my naive question.

I have got `output` dir, which containing some `.cc` and `.h` files. But I have no idea about how to arrange them.

Thanks for your attention.

**Comment by andyarvanitis** [comment]
Not a bother at all. Are you asking whether the generated code is like "hand-coded" code? The goal is to make the output C++ as readable (and as easy to debug) as possible, but I wouldn't say it looks like something a human wrote, mostly because of the variant typing used. Please let me know if I misunderstood your question, though.

**Comment by suzumiyasmith** [comment]
Actually, I am considering how to generate a c++ project which could be directly imported to some kinds of IDEs. 

As known, after running the make command building a pure11 project, an `output` dir is generated, which contains `.cc` and `.h` files. I wonder how can I build and run them, in computers only having c++ toolchain. In other words, if I write a project in pure11, but I have to make the c++ codes working on another computer which can only build c++ projects.

I wonder if it is possible to generate a c++ projects only contains `.cpp` and `.h`, which could be built by a `make` file.

**Comment by andyarvanitis** [comment]
Ok, I think I understand your question. The files created in `output` are already regular C++11 source files (for basically any platform with just a C++11 compiler toolchain, no other requirements). They have `.cc` (C++ source) and `.hh` (header) file extensions. You should be able to use them directly in a `make`- or IDE- based project. If you are using `make` and your own custom/project `Makefile` doesn't search for `.cc` files, you could either modify your `Makefile` or rename the `*.cc` files to `*.cpp`. As for IDEs, most of the ones that I've tried recognize `.cc` as well as `.cpp`. Hope that helps.

**Comment by suzumiyasmith** [comment]
Thanks for your explanation and patience.

I think I will possibly following your advice write some simple shell scripts to automate generating c++ project from `output` folder.
